### ISSUE TITLE
Bookmarked, Downloaded Episode Not Playing

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/se-daily-iOS#105]
To recreate on iPhone 6S:
1. Bookmark several episodes
2. Bookmark and download an episode (I used "Modern War with Peter Warren Singer")
3. Start playing a different episode
4. Go to Bookmarks, try to play "Modern War with Peter Warren Singer"

On my phone, clicking Play did nothing. Restarting application did nothing.

**Comment by justinctlam** [comment]
Which version of the app are you using? We should have some sort of About page to help diagnose which version people are encountering issues.

**Comment by crablar** [comment]
Most recent version in current TestFlight.

**Comment by jasonify** [comment]
Ahh, I believe I see part of the problem. Though there could be multiple bugs.

The problem seems to be with the search controller and `audioOverlayDelegate` being null in  the HeaderView so the play action never happens. I imagine the same is true in other controllers.

 I'll push a fix up for this as soon as possible.

**Comment by justinctlam** [comment]
This should be fixed now?
