### ISSUE TITLE
[Improvement] Loading cursor overlaps with the list of items

### ISSUE THREAD

**Issue by justinctlam** [SoftwareEngineeringDaily/se-daily-iOS#13]
The loading indicator overlaps with the collection view when items are visible. Consider a different kind of loading indicator to prevent visual collision.

**Comment by themisterholliday** [comment]
I like this, do you have a good example we could go off?

**Comment by justinctlam** [comment]
My immediate thought is to use the built in loading indicator that is a bar that transition from left to right, similar to the Safari loading bar.

Also to consider is to use skeleton loading (aka shimmering boxes) instead of the spinner for loading the cell images :)

**Comment by themisterholliday** [comment]
I like that, we're not tracking progress for the API request though. It could just be fake of course. I'd rather use the circle loading and just have it in a different position.

Glad you brought up skeleton loading though. So what if we have the skeleton for the initial load and when scrolling down too far you can see the loading indicator? I say scrolling down too far because right now I start loading new podcasts before the user will get to the bottom of the current podcasts.

Here's a perfect library we could update and use: https://github.com/gonzalonunez/Skeleton

**Comment by justinctlam** [comment]
If you like using a spinner, Imgur app seems to do a good job. Their interface doesn’t look too different from our app.

**Comment by themisterholliday** [comment]
Sweet I'll check it out 👍

**Comment by themisterholliday** [comment]
Fixed in this PR: https://github.com/SoftwareEngineeringDaily/se-daily-iOS/pull/23
