### ISSUE TITLE
[Bug] Playback at any speed greater than 1x sounds muffled

### ISSUE THREAD

**Issue by justinctlam** [SoftwareEngineeringDaily/se-daily-iOS#30]
Playback at any speed greater than 1x sounds muffled. I tried playing on 1.5x in the default Apple podcast app and it sounds much more clear. Is this possible to fix? 

Also, where is the 1.5x option?

**Comment by themisterholliday** [comment]
Could you do `pod update` and see if KoalaTeaPlayer updates. Then try? This is an avPlayer issue. 

2.5 and 3.0 should be muffled but it's the way the timePitchAlgorithm works. 

I just added some options to show the feature. I'd like to use some custom view instead of the activity sheet in the future with options to step up by `0.1`.

**Comment by justinctlam** [comment]
0.1.7 seems to work better. I think you will need to push the new podspec for KoalaTeaPlayer. Right now, the latest only grabs 0.1.6.

**Comment by themisterholliday** [comment]
I'll double check the repo and see what's up. But the audio sounds good now?

**Comment by justinctlam** [comment]
I believe so, as long as we use 0.1.7.

Speaking of cocoa pods version number, may I suggest we specify the exact version number in the podfile? It is better to code against a fixed version because newer versions can easily break existing work if there are bugs or significant changes.

**Comment by themisterholliday** [comment]
Fantastic suggestion. That'll fix any more pod issues we have. I'll create a new issue to fix that.
