### ISSUE TITLE
Is Disk the right tool for caching backend data?

### ISSUE THREAD

**Issue by justinctlam** [SoftwareEngineeringDaily/se-daily-iOS#45]
Disk doesn't seem to have anyway to update an individual item. It appears you have to fetch all the data for the podcast, update an individual item, clear the file, then rewrite the entire array back into Disk.  Is this better than using a db like sqllite, realm or coredata?

Also, Disk doesn't seem to support querying for data based on a predicate/condition.

**Comment by themisterholliday** [comment]
I'm open to seeing what an sqlite or coredata implementation would look like. I haven't used those in a lot of projects. Realm is too large and we wouldn't use nearly half the features it provides. 

I'm also trying to avoid writing extra data models to exclusively interact with the persistence layer. Disk seems like a good option to me since it uses Codable objects and it is light. I'm not sure how expensive it is to fetch, update, then rewrite the data but if that is too much I'm more open to another solution. 

I don't see a ton of difference from retrieving all the objects and filtering the array, but once again, open to seeing other solutions if they're measurably better.

**Comment by justinctlam** [comment]
I understand. Let's stick with what we have. We can try do the fetch, update, rewrite for the time being and re-evaluate if it ever becomes an issue. Here are some example scenarios:

1) There is data on posts already in Disk. Fetch new data. Retrieve existing data, combine with new data, replace duplicates with the newest data, rewrite back into Disk.

2) There is data on posts already in Disk. User upvotes or downvotes. Retrieve existing data, update the individual post, rewrite data back into Disk.

**Comment by themisterholliday** [comment]
This should be an ongoing discussion but for the sake of cleaning up I'm going to close this issue. We should break up specific issues related to this one.

Also some of the issues raised are fixed in #47
