### ISSUE TITLE
Any chance of getting this app on IOS 9

### ISSUE THREAD

**Issue by lestephane** [SoftwareEngineeringDaily/se-daily-iOS#55]
I'd love to be able to use the app on my Iphone 4S. This would make it usable for a wider audience too,
as a lot of people don't necessarily want (or can)  upgrade to the latest greatest (buggiest) phones.

Failing that, is there's dev documentation, maybe i can take it on. Thoughts?

**Comment by TheHollidayInn** [comment]
I believe the issue here is that Xcode no longer supports anything under iPhone 5. I'll let @themisterholliday  comment on if there are other ways/reasons.

The readme file has help getting set up with xcode and pods. The architecture is primarily MVVM. Feel free to ask any questions here and on Slack :D

**Comment by themisterholliday** [comment]
Xcode still supports iOS 9 development so this is 100% doable.

I'm in the process of updating one library the project is dependent on and then iOS 9 support should be a snap.
