### ISSUE TITLE
[Feature] - Play next queue

### ISSUE THREAD

**Issue by seanfalconer80** [SoftwareEngineeringDaily/se-daily-iOS#61]
I'd love any option to queue up multiple podcast episodes to be played automatically in sequence.

**Comment by jacobworrel** [comment]
I second that. Some kind of option to save episodes to a playlist and then play them in sequence would be amazing.

**Comment by justinctlam** [comment]
@crablar @themisterholliday @TheHollidayInn Do you guys think we should add a playlist feature? Another tab to show playlists?

**Comment by TheHollidayInn** [comment]
I'd be down. We could have a queue like that is the default playlist, the let users create and add to other queues (with some tag to group them in a playlist?)

**Comment by crablar** [comment]
@justinctlam Could you see yourself making multiple playlists? Or is the single playlist "Bookmarked/Downloaded" experience enough of the functionality?

**Comment by justinctlam** [comment]
@crablar It's always good to design for the "many" rather than for the "one". So in this case, it's good to build it for multiple playlists and if we determine it's not useful we can scale it to 1 rather than "n".  I do think having multiple playlists can be useful. Say you want a AI playlists, a Crypto playlists, a Distributed Computing playlist, etc... You can also have a bookmarked playlist, or a download playlist.
